name: Hello World!

on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"
          ls
          date
      - name: Say goodbye
        run: echo "Goodbye World!"
  ab_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Welcome abdu
        run: |
          echo "Hello abdu!"
          ls -a
          date
       
         
            